# Mental Models System - Grafana Datasources
apiVersion: 1

datasources:
  # PostgreSQL - Primary data source for mental models
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: mental_models
    user: oligarch
    secureJsonData:
      password: munger_wisdom_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true

  # Prometheus - Metrics data source
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    editable: true
